# SPDX-FileCopyrightText: 2024 Dom Rodriguez <shymega@shymega.org.uk>
#
# SPDX-License-Identifier: CC0-1.0

---
name: CI - Android

on:
  workflow_call:

env:
  IS_OUTSIDE_BSP: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: 'gradle'
    - run: ./gradlew build

  assembleDebug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: 'gradle'
    - run: ./gradlew assembleDebug

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: 'gradle'
    - run: ./gradlew test
